apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wmua
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wmua
    app.kubernetes.io/part-of: ci10t-776-0023-app
  name: devfile-sample-wmua
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wmua
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wmua
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0023-tenant/ci10t-776-0023-app/devfile-sample-wmua@sha256:3b3e0587ff2e9bd33c9319f00b46cdfff82991eed6944317863d3f31ba9e86ef
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
